# action.yml
name: 'cargo contracts'
description: 'Cargo command wrapper'
inputs:
  cargo-cmd:  # id of input
    description: 'Cargo command'
    required: true
    default: 'cargo --version'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.cargo-cmd }}
