name: Build and Test Smart Contracts

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    steps:
      - name: SHA
        run: |
          echo GIT: ${GITHUB_SHA} ${GITHUB_HEAD_REF} ${{ github.event.pull_request.head.sha }}
          export
      - uses: actions/checkout@v3
        with:
          path: "examples/hello"
      # - name: Build hello contract
      #   uses: simonsso/cargo-contract@tryci
      #   with:
      #     cargo-cmd: cargo contract build --verbose
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: contracts
          path: |
             target/ink/**/*.contract
