name: Build and Test Smart Contracts

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    steps:
      - uses: actions/checkout@v3
        with:
          path: "examples/hello"
<<<<<<< HEAD
      - name: Build and Test simple-timed-lock
        uses: simonsso/cargo-contract@${GITHUB_SHA}
=======
      - name: Build hello contract
        uses: simonsso/cargo-contract@master
>>>>>>> 5b9bda0f4b8f81f340839f1821b1c8dc193d087b
        with:
          cargo-cmd: cargo contract build --verbose
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: contracts
          path: |
             target/ink/**/*.contract
